#!/bin/bash

#!/bin/bash

DL=~/Downloads/*
DT=Desktop/*.png
TR=~/.Trash/*

if ! command -v trash &> /dev/null
  then
		echo "Trash command not found. Using 'rm' instead." 
    echo "-----"
    test -f "$DL" && rm -rf "$DL" && echo "Downloads cleaned."
		test -f "$DT" && rm     "$DT" && echo "Desktop cleaned."
		test -f "$TR" && rm -rf "$TR" && echo "Trash cleaned."
    echo "-----"
		echo "Cleaned Desktop, Downloads, and Trash using 'rm'."
  else
		echo "Using 'trash'."
    echo "-----"
    test -f "$DL" && trash "$DL" && echo "Downloads cleaned."
		test -f "$DT" && trash "$DT" && echo "Desktop cleaned."
		test -f "$TR" && trash -ey   && echo "Trash cleaned."
    echo "-----"
		echo "Cleaned Desktop, Downloads, and Trash using 'trash'."
fi
