#!/bin/bash

if ! command -v fd &> /dev/null
  then
    echo "##############################################"
    echo "fd command not found -- terminating."
    echo "##############################################"
    exit 1
elif ! command -v fd &> /dev/null
  then
    echo "##############################################"
    echo "trash command not found -- terminating."
    echo "##############################################"
    exit 1
else
    echo "##############################################"
fi

DL=~/Downloads
DT=~/Desktop
TR=~/.Trash

if [[ `fd . $DL --prune | wc -l` -gt 0 ]]
  then
    fd . $DL --prune --no-ignore-vcs -X trash
    echo "- Cleaned `basename $DL`."
  else
    echo "`basename $DL` is already empty."
fi

if [[ `fd .png $DT --prune | wc -l` -gt 0 ]]
  then
    fd .png $DT --prune --no-ignore-vcs -X trash
    echo "- Cleaned `basename $DT`."
  else
    echo "`basename $DT` is  already empty."
fi

trash -e

echo "##############################################"
