abbr -a -U -- g git
abbr -a -U -- ga 'git add'
abbr -a -U -- gaa 'git add --all'
abbr -a -U -- gau 'git add -u'
abbr -a -U -- gcm 'git commit -m'
abbr -a -U -- gp 'git push'
abbr -a -U -- gr 'git pull --rebase'
abbr -a -U -- gs 'git status'
abbr -a -U -- s 'snakemake --cores 4'
abbr -a -U -- y yadm
abbr -a -U -- ya 'yadm add'
abbr -a -U -- yau 'yadm add -u'
abbr -a -U -- ycm 'yadm commit -m'
abbr -a -U -- yp 'yadm push'
abbr -a -U -- yr 'yadm pull --rebase'
abbr -a -U -- ys 'yadm status'
